### ISSUE TITLE
Publish deprecation notice

### ISSUE THREAD

**Issue by kevinburkeotto** [freewil/scmp#5]
Node.js has a `timingSafeEqual` function built in as of version 6.6.0: https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b

It seems better to a) use that function if it's available and/or b) note in the README that people don't need to load a third party library to do that anymore.

**Comment by freewil** [comment]
Did you read the readme? 😄

**Comment by kevinburkeotto** [comment]
ah, apologies, I scanned it but didn't see it

**Comment by freewil** [comment]
Haha no problems - thanks for the note anyway :)
